# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0003_auto_20180502_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='date',
            field=models.FloatField(blank=True, default=False),
        ),
    ]
