# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0006_remove_devicemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 11, 19, 32, 535109)),
        ),
    ]
