# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0007_devicemodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='date_created',
            field=models.DateTimeField(default='1525260191'),
        ),
    ]
