# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0008_auto_20180502_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='date_created',
            field=models.FloatField(default=False),
        ),
    ]
