# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0009_auto_20180502_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='date_created',
        ),
    ]
