# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0010_remove_devicemodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='payment_expiry',
            field=models.FloatField(default=False),
        ),
    ]
