# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0011_devicemodel_payment_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='payment_expiry',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
