# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0013_auto_20180503_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='payment_expiry',
            field=models.DateTimeField(),
        ),
    ]
