# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0016_auto_20180503_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ('payment_expiry',)},
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='payment_expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
